# Generated by Django 4.2.5 on 2023-10-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=120)),
                ('data_nascimento', models.DateTimeField()),
                ('CEP', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('alergias', models.TextField(blank=True)),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('email_resp', models.EmailField(max_length=254)),
                ('telefone_resp', models.CharField(max_length=20)),
            ],
        ),
    ]
