# Generated by Django 4.2.6 on 2023-10-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Florescer_app', '0003_alter_crianca_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crianca',
            name='sobrenome',
        ),
    ]
