# Generated by Django 4.2.5 on 2023-11-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Florescer_app', '0004_remove_crianca_sobrenome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=5)),
                ('CEP', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('alergias', models.TextField(blank=True)),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('email_resp', models.EmailField(max_length=254)),
                ('telefone_resp', models.CharField(max_length=20)),
            ],
        ),
    ]
