# Generated by Django 4.2.5 on 2023-11-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Florescer_app', '0006_rename_email_resp_voluntario_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('arrecadacao', 'Arrecadação'), ('gasto', 'Gasto')], max_length=20)),
            ],
        ),
    ]
