# Generated by Django 4.2.5 on 2023-10-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Florescer_app', '0002_crianca_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
